name: Pylint

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Run Pylint
      run: |
        pylint getai/*.py > pylint-report.txt || true
    - name: Upload Pylint Report
      uses: actions/upload-artifact@v3
      with:
        name: pylint-report-${{ matrix.os }}-${{ matrix.python-version }}
        path: pylint-report.txt
    - name: Display Pylint Report
      run: cat pylint-report.txt
